config/routes.rb
SampleApp::Application.routes.draw do
  get "sprint_teams/new"
  get "sprint_teams/create"
  get "sprint_teams/edit"
  get "sprint_teams/update"
  get "sprint_teams/delete"
  get "sprints/new"
  get "sprints/destroy"
  get "sprints/create"
  get "sprint_backlog_items/new"
  get "sprint_backlog_items/edit"
  get "sprint_backlog_items/create"
  get "sprint_backlog_items/update"
  get "sprint_backlog_items/destroy"
  get "backlog_items/new"
  get "backlog_items/destroy"
  get "backlog_items/create"
  get "projects/show"
  get "projects/new"

  get "projects/update"
  get "projects/delete"
  resources :users
  root "static_pages#home"
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :projects
  resources :teams
  resources :backlog_items
  resources :sprint_backlog_items
  resources :sprints
  resources :sprint_teams

  get 'sprint_backlog_items/new/:id' => 'sprint_backlog_items#new'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>О продукте</h1>
<p>
  В даний час в області сучасної та своєчасної розробки програмних додатків одними з найважливіших критеріїв є швидкість написання програми та правильний розподіл завдань між розробниками. У житті будь-якої компанії буває момент, коли кількість справ, яке змушені контролювати співробітники і особливо керівництво стає таким, що перевершують можливості людської пам'яті.
  Буває й інша ситуація подібна до цієї – відділ, що складається більш ніж з 15-20 співробітників, які працюють одночасно над одним завданням – складна структура для управління, і без спеціальних засобів проконтролювати їх роботу надзвичайно складно.
  <br>
  Дана робота присвячена проектуванню і розробці продукту, який дасть змогу прискорити розробки різних програмних проектів.
  <br>
  Програма призначена для того, щоб: викладачі та розробники – студенти могли контролювати всі процеси, бачити проект в цілому; щоб викладачі могли ефективно організувати роботу студентів, призначати їм завдання, мати миттєві засоби контролю виконання; для ефективних комунікацій між всіма учасниками розробки; для сбереження різної протокольної інформації, аналізу витраченого користувачами часу на певну задачу; для контролю за термінами виконання.
  Метою дипломної роботи є створення спрощеного безкоштовної системи контролю задач, використання якої обумовлюється потребами університету. Областю застосування даного програмного продукту є Дніпропетровский національний университет зализничного транспорту імені академіка В.Лазаряна (ДНУЗТ), а саме використання в межах таких дисциплін кафедри ТК, як:
 <br>
  1. «Програмування та САПР ПО » (4 курс).
  <br>
  2. «Компонентне і розподілене програмування» (5 курс).

</p>

app/views/static_pages/contact.erb
<%provide(:title,'Contact')%>
<h1>Контакты</h1>
<p>
  e-mail:savinov_evg@ua.fm
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Помощь</h1>
<p>
    <ol>
       <li>Зарегистрируйтесь/авторизируйтесь</li>
       <li>Нажмите Учетная запись->профиль</li>
       <li>Создавайте проект</li>
       <li>Со страницы профиля нажмите ссылку на созданный проект</li>
       <li>Создавайте необходимое содержимое для проекта</li>
       <li>Работайте</li>
    </ol>
</p>

app/views/static_pages/home.html.erb
<%provide(:title,'Home')%>
<div class="center hero-unit">
  <h1> АРМ "Команда"</h1>

  <h2>
Приветствуем! Авторизируйтесь, если вы зарегистрированы, или пройдите
    регистрацию прямо сейчас.
  </h2>
<%if current_user.nil? %>
  <%= link_to "Регистрация", signup_path, class: "btn btn-large btn-primary" %>

      <% else %>
      <%= link_to "Перейти к профилю", user_path(current_user), class: "btn btn-large btn-primary" %>
 <% end %>
      </div>
<%#= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>