config/routes.rb
SampleApp::Application.routes.draw do
  get "sprint_teams/new"
  get "sprint_teams/create"
  get "sprint_teams/edit"
  get "sprint_teams/update"
  get "sprint_teams/delete"
  get "sprints/new"
  get "sprints/destroy"
  get "sprints/create"
  get "sprint_backlog_items/new"
  get "sprint_backlog_items/edit"
  get "sprint_backlog_items/create"
  get "sprint_backlog_items/update"
  get "sprint_backlog_items/destroy"
  get "backlog_items/new"
  get "backlog_items/destroy"
  get "backlog_items/create"
  get "projects/show"
  get "projects/new"

  get "projects/update"
  get "projects/delete"
  resources :users
  root "static_pages#home"
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :projects
  resources :teams
  resources :backlog_items
  resources :sprint_backlog_items
  resources :sprints
  resources :sprint_teams

  get 'sprint_backlog_items/new/:id' => 'sprint_backlog_items#new'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :teams
  has_many :backlog_items
  has_many :sprints
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :user_email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :project_url, uniqueness: { case_sensitive: false }, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :signed_in_user #, only: [:index, :edit, :update, :create]
  def show
    @project = Project.find(params[:id])
    if !params[:user].nil?
      @user = User.find(params[:user])
    end
    if !params[:backlog_item].nil?
      @backlog_item = BacklogItem.find(params[:backlog_item])
    end

    if !params[:sprint_backlog_item].nil?
      @sprint_backlog_item = SprintBacklogItem.find(params[:sprint_backlog_item])
    end
    if !params[:user_name].nil?
      @user_selected = User.find(params[:user_name])
    end
lolka = 0
  end

  def new
    @project = Project.new
  end

  def destroy
    Project.find(params[:id]).destroy
    flash[:success] = "Project deleted."
    redirect_to current_user
  end

  def index
  end

  def create
    @project = Project.new(project_params)
    @user =current_user
    if !@user.nil?
      @project.user_id=@user.id
      @project.user_email=@user.email
    end
    if !@user.nil?&&@project.save
      flash[:success] = "Project was succesfully created!"
      redirect_back_or current_user
    else
      render 'new'
    end
  end


  def edit
    #@user = User.find(params[:id])
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:success] = "Project updated"
      redirect_to @project
    else
      render 'edit'
    end
  end

  private

  def project_params
    params.require(:project).permit(:project_url, :user_email, :project_story)
  end



  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/destroy.html.erb
<h1>Projects#delete</h1>
<p>Find me in app/views/projects/delete.html.erb</p>

app/views/projects/edit.html.erb
<% provide(:title, 'Update project') %>
<h1>Изменить описание проекта</h1>
<div class = "something">

</div>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@project) do |f| %>
        <%#= render 'shared/error_messages' %>
        <% if @project.errors.any? %>
            <div id="error_explanation">
              <div class="alert alert-error">
                The form contains <%= pluralize(@project.errors.count, "error") %>.
              </div>
              <ul>
                <% @project.errors.full_messages.each do |msg| %>
                    <li>* <%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <%= f.label "Описание проекта" %>
        <%= f.text_area :project_story %>

        <%= f.submit "Обновить проект", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<% provide(:title, 'New Project') %>
<h1>Новый проект</h1>
<div class = "something">

</div>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@project) do |f| %>
        <%#= render 'shared/error_messages' %>
        <% if @project.errors.any? %>
            <div id="error_explanation">
              <div class="alert alert-error">
                The form contains <%= pluralize(@project.errors.count, "error") %>.
              </div>
              <ul>
                <% @project.errors.full_messages.each do |msg| %>
                    <li>* <%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <%= f.label "Название проекта" %>
        <%= f.text_field :project_url %>

        <%#= f.label :user_email %>
        <%#= f.text_field :user_email %>

        <%= f.label "Описание проекта" %>
        <%= f.text_area :project_story %>

        <%= f.submit "Создать новый проект", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<% provide(:title, @project.project_url) %>

<h1><span class="label label-primary">Проект <%=@project.project_url%></span></h1>

  <h2><span class="label label-primary">Создатель <%=@project.user_email%></span></h2>

<h4><%= @project.project_story %></h4>
<!-- список пользователей на проекте-->
<div class="btn-group">
  <button type="button " class="btn btn-info dropdown-toggle" data-toggle="dropdown">
    Пользователи на проекте <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <%@project.teams.each do |team|%>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%=link_to "#{User.find(team.user_id).email}", project_path(user_name:team.user_id)%></a></li>
        <li role="presentation"> <a role="menuitem" tabindex="-1" href="#">
          <% if current_user.email==@project.user_email%>
              <%= link_to "Удалить пользователя из команды", team, method: :delete,
                          data: { confirm: "You sure?" }%>
              <li class="divider"></li>
          <%end%> </a></li>


    <% end %>
  </ul>
</div>
<!-- Список задач на проекте -->
<div class="btn-group">
  <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
    Задачи на проекте <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <%@project.backlog_items.each do |item|%>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%=link_to "#{item.item_title}", project_path(backlog_item: item)%></a></li>
        <li role="presentation"> <a role="menuitem" tabindex="-1" href="#">
          <% if current_user.email==@project.user_email%>
              <%= link_to "Удалить задачу", item, method: :delete,
                          data: { confirm: "You sure?" }%>
              <li class="divider"></li>
          <%end%> </a></li>
    <% end %>
  </ul>
</div>
<!-- Боковая панель команды на проекте-->
<p>
<div class="box2">
  <div class="panel panel-default">
    <div class = "left-panel-width">
            <div class="panel-body">
                <div class="list-group">
                 <a href="#" class="list-group-item active">
                     Команда на проекте:
                     </a>
                     <%@project.teams.each do |team|%>

                      <%=link_to "#{User.find(team.user_id).email}", project_path(user_name:team.user_id), class: "list-group-item"%>
                        <% if current_user.email==@project.user_email%>
                            <%= link_to "Удалить из команды", team, method: :delete,
                            data: { confirm: "You sure?" }, class: "list-group-item"%>
                        <%end%>
                        <a href="#" class="list-group-item active"> </a>
                     <%end%>
                </div>

<!-- Боковая панель задач-->

              <div class="list-group">
                <a href="#" class="list-group-item active">
                  Задачи:
                </a>
                <%@project.backlog_items.each do |item|%>
                  <%=link_to "#{item.item_title}", project_path(backlog_item: item), class: "list-group-item" %>
                    <% if current_user.email==@project.user_email%>
                        <%= link_to "Удалить задачу", item, method: :delete,
                                    data: { confirm: "You sure?" }, class: "list-group-item"%>
                    <%end%>
                    <a href="#" class="list-group-item active"> </a>
                <%end%>
              </div>
            </div>
      </div>
    </div>
</div>



<div class="panel panel-default box2">
</p>
  <div class="table-width">
  <div class="bs-example">
    <%if !@user_selected.nil?%>

        <table class="table table-bordered">
          <thead>
          <tr>
            <th>Почтовый адрес пользователя</th>
            <th>Никнейм пользователя</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td><%=@user_selected.email %></td>
            <td><%=@user_selected.name %></td>
          </tr>

          </tbody>
        </table>

    <%end%>
    <!-- Таблица спринтов-->
    <table class="table table-bordered">
      <thead>
      <tr>
        <th>Спринт</th>
        <th>Дата начала</th>
        <th>Дата окончания</th>
        <th>Список задач</th>
      </tr>
      </thead>
      <tbody>
      <%@project.sprints.each do |sprint|%>
      <tr>
        <td>
          <%=sprint.title %> <% if current_user.email==@project.user_email%>
              <%= link_to "X", sprint, method: :delete,
                          data: { confirm: "You sure?" }%>
          <%end%>
        </td>
        <td>
          <%=sprint.datestart %>
        </td>
        <td>
          <%=sprint.dateend %>
        </td>
        <td>
          <div class="btn-group">
            <button type="button " class="btn btn-info dropdown-toggle" data-toggle="dropdown">
              Задачи на спринте <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <%sprint.sprint_teams.each do |item|%>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= link_to "#{BacklogItem.find(item.backlog_item_id).item_title}",
                                                      project_path( backlog_item: item.backlog_item_id)%>
                    <% if current_user.email==@project.user_email%>
                        <%= link_to "Удалить", item, method: :delete,
                                    data: { confirm: "You sure?" }%>
                    <%end%>
                  </a></li>
                  <li class="divider"></li>
              <% end %>
            </ul>
          </div>
        </td>
      </tr>
          <tr>
            <td colspan="4">
              <%=link_to "Изменить спринт", edit_sprint_path(sprint), class: "btn btn-info" %>
            </td>
          </tr>
          <% end%>

      </tbody>
    </table>


    <!-- Таблица с задачей-->
   <% if !@backlog_item.nil? %>

        <table class="table table-bordered">
          <thead>
          <tr>
            <th  >#</th>
            <th colspan="3">Задача <%=@backlog_item.item_title %></th>
            <th >Описание задачи</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td>Тип</td>
            <td colspan="3"><%=@backlog_item.item_type%></td>
            <td rowspan="4" colspan="3"><%=@backlog_item.item_description%></td>

          </tr>
          <tr>
            <td>Состояние</td>
            <td colspan="3"><%=@backlog_item.item_state%></td>

          </tr>
          <tr>
            <td>Окончание</td>
            <td colspan="3"><%=@backlog_item.item_deadline%></td>
          </tr>
          <tr>
            <td>Закреплено за</td>
            <td colspan="3"><%=User.find(@backlog_item.user_id).email%></td>
          </tr>
          <tr>
            <td>Подзадачи</td>
            <td colspan="3">
              <div class="btn-group">
                <button type="button " class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                  Выбрать подзадачу<span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <%@backlog_item.sprint_backlog_items.each do |sprint_item|%>
                      <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%=link_to "#{SprintBacklogItem.find(sprint_item.id).activity}",
                                                                                project_path( backlog_item: sprint_item.backlog_item, sprint_backlog_item:sprint_item )  %>
                        <% if current_user.email==@project.user_email%>
                            <%= link_to "Удалить", sprint_item, method: :delete,
                                        data: { confirm: "You sure?" }%>
                        <%end%>
                      </a></li>
                      <li class="divider"></li>
                  <% end %>
                </ul>
              </div>
            </td>
            <td><%=link_to "Изменить задачу", edit_backlog_item_path(@backlog_item), class: "btn btn-info"%></td>
          </tr>


          </tbody>
        </table>
   <% end %>


    <!-- Таблица с подзадачей-->
    <% if !@sprint_backlog_item.nil? %>

        <table class="table table-bordered">
          <thead>
          <tr>
            <th  >#</th>
            <th colspan="3">Подзадача <%=@sprint_backlog_item.activity  %></th>
            <th >Описание подзадачи</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td>Состояние</td>
            <td colspan="3"><%=@sprint_backlog_item.state%></td>
            <td rowspan="5" colspan="3"><%=@sprint_backlog_item.subtask_description%></td>

          </tr>


          <tr>
            <td rowspan="2" colspan="4"><%=link_to "Изменить подзадачу", edit_sprint_backlog_item_path(@sprint_backlog_item),
                                                   class: "btn btn-info"%></td>

          </tr>


          </tbody>
        </table>
    <% end %>





  </div>
  </div>
</div>

<table class="table my_table">
  <tbody>
  <tr>
    <td> <%= link_to "Добавить задачу", backlog_items_new_path(project: @project), class: "btn btn-default btn-block "%></td>
    <td> <%= link_to "Добавить подзадачу", sprint_backlog_items_new_path(project: @project), class: "btn btn-default btn-block "%></td>
  </tr>


  <tr>
    <td>  <%= link_to "Добавить спринт", sprints_new_path(project: @project), class: "btn btn-default btn-block "%></td>
    <td>  <%= link_to "Добавить задачу к спринту", sprint_teams_new_path(project: @project), class: "btn btn-default btn-block "%></td>
  </tr>

  <tr>
    <td> <%= link_to "Добавить пользователя в команду проекта", new_team_path, class: "btn btn-default btn-block"%></td>
    <td> <%= link_to "Редактировать описание проекта", edit_project_path(@project), class: "btn btn-default btn-block"%></td>
  </tr>
  </tbody>
</table>