config/routes.rb
SampleApp::Application.routes.draw do
  get "sprint_teams/new"
  get "sprint_teams/create"
  get "sprint_teams/edit"
  get "sprint_teams/update"
  get "sprint_teams/delete"
  get "sprints/new"
  get "sprints/destroy"
  get "sprints/create"
  get "sprint_backlog_items/new"
  get "sprint_backlog_items/edit"
  get "sprint_backlog_items/create"
  get "sprint_backlog_items/update"
  get "sprint_backlog_items/destroy"
  get "backlog_items/new"
  get "backlog_items/destroy"
  get "backlog_items/create"
  get "projects/show"
  get "projects/new"

  get "projects/update"
  get "projects/delete"
  resources :users
  root "static_pages#home"
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :projects
  resources :teams
  resources :backlog_items
  resources :sprint_backlog_items
  resources :sprints
  resources :sprint_teams

  get 'sprint_backlog_items/new/:id' => 'sprint_backlog_items#new'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%=link_to "АРМ \"Команда\"", root_path%>
    by Savinov Evgen
  </small>
  <nav>
    <ul>
      <li><%= link_to "О продукте",   about_path, class: "btn btn-info" %></li>
      <li><%= link_to "Контакты", contact_path, class: "btn btn-info" %></li>
      <li><a href="http://news.railstutorial.org/" class="btn btn-info">Новости Rails</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "АРМ \"Команда\"", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Начальная страница", root_path %></li>
          <li><%= link_to "Помощь", help_path %></li>
          <% if signed_in? %>
              <%if current_user.admin==true %>
                  <li><%= link_to "Пользователи", users_path %></li>
              <%end%>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Учетная запись <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Профиль", current_user %></li>
                  <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Выйти", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Авторизироваться", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<%= render "layouts/shim"%>
</head>
<body>
<%= render "layouts/header"%>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
      <%#= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>